name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/NOTES.png"
  min_sdk_android: 21 

flutter_native_splash:
  android: true
  ios: true
  color: "#121212"
  image: "assets/NOTES.png"

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/NOTES.png
